apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp-billing-slack-notify.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcp-billing-slack-notify.name" . }}
    helm.sh/chart: {{ include "gcp-billing-slack-notify.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels.secret }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.secret }}
  annotations:
    {{- with .Values.annotations.secret }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  service_account.json: {{ required "GCP service account key for BigQuery" .Values.secrets.gcp_sa_key | b64enc | quote }}
  slack_webhook: {{ required "Slack webhook" .Values.secrets.slack_webhook | b64enc | quote }}
